import Image from "next/image";
import Link from "next/link";
import styles from "./WorldPanels.module.css";

export default function AboutPanel() {
  return <div className={styles.aboutGrid}>
    <div className={`${styles.pane} ${styles.portrait}`}><div className={styles.paneBar}>01 / THE PERSON <span>DUBLIN, IE</span></div><div className={styles.portraitImage}><Image src="/about/about1.png" alt="Nami peeking through her fingers in a playful portrait" fill sizes="(max-width: 700px) 80vw, 32vw" style={{objectFit:"contain"}} priority /><div className={styles.portraitInset}><Image src="/about/about2.jpeg" alt="Nami holding two vintage telephone receivers in a record shop" fill sizes="140px" style={{objectFit:"cover"}} /></div></div><p>Naransuvd Enkhjargal<span>Friends call me Nami.</span></p></div>
    <section className={`${styles.pane} ${styles.bio}`}><p className={styles.eyebrow}>DESIGNER × DEVELOPER</p><h2>Design with purpose.<br/><em>Build with precision.</em></h2><p>I’m Nami, a UI/UX designer and front-end developer based in Dublin. I turn complex requirements into clear interfaces and bring them to life in code — connecting product thinking, visual design, and implementation.</p><p>With a master’s degree in Interactive Digital Media, I bring research, interaction design, and development into one process. Every decision serves a clear goal: a product that is intuitive, cohesive, and considered in every detail.</p><div className={styles.actions}><a className={styles.primary} href="/resume.pdf" target="_blank" rel="noopener noreferrer">View résumé ↗</a><Link href="/contact" replace scroll={false}>Let’s talk ↗</Link></div></section>
    <section className={styles.pane}><div className={styles.paneBar}>02 / HOW I WORK</div><div className={styles.padded}><h3>From insight to execution.</h3><ol className={styles.steps}><li><b>Understand</b><span>Define the problem, understand the people, and establish clear priorities.</span></li><li><b>Shape</b><span>Translate insights into focused flows, prototypes, and visual systems.</span></li><li><b>Build & refine</b><span>Implement the experience, validate decisions, and refine the details.</span></li></ol></div></section>
    <section className={styles.pane}><div className={styles.paneBar}>03 / MY TOOLKIT</div><div className={styles.padded}><h3>Design expertise. Technical range.</h3><div className={styles.chips}>{["Figma", "UI / UX", "Prototyping", "React", "React Native", "Next.js", "JavaScript", "Firebase"].map(skill=><span key={skill}>{skill}</span>)}</div><Link className={styles.textLink} href="/projects" replace scroll={false}>See the work behind the tools ↗</Link></div></section>
  </div>;
}
